### ISSUE TITLE
Fixing Description of GCloud instance Creation

### ISSUE THREAD

**Issue by burakbayramli** [GoogleCloudPlatform/ipython-soccer-predictions#7]
I folllowed all the steps described in README.

```
gcloud compute instances create ipy-predict \
  --image https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20140522 \
  --zone=us-central1-a --machine-type n1-standard-1 --scopes storage-ro bigquery
```

This will give an error for not finding the project name.  Then I supply the project name I created earlier on the dashboard, I call it world-cup-1 on my dashboard. Then,

Then I supply the project name using --project=world-cup-1, this time I get 

```
ERROR: (gcloud.compute.instances.create) some requests did not succeed:
 - Project projects/world-cup-1 cannot accept requests to insert while in an inactive billing state.  Billing state may take several minutes to update.
```

I thought I could evaluate this without enabling billing.. 

I understand this project is a commercial of sorts for Google Cloud services. But all I am  interested in is seeing the machine learning data and code; can you find a way to share this data as pure CSV files, and show the awesome BigQuery code that created it just as documentation maybe so we can gawk at it seperately?

Maybe a better way is having seperate instructions for executing BQ code on development machines through SDK, so we can at leasty dump the file on disk without the need to creating instances on GC.

**Comment by abdennour** [comment]
It is a bad user experience when you block users because of billing info outdated  , in the same time  this user  is seeing at the top of the page : 

```
You have $300.00 in credit and 271 days left of your free trial
```
